**NUMPY**

In [3]:
import sys
import numpy as np

In [4]:
# Creating an Array - One Dimentional Array (Vector)
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [13]:
a = np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [14]:
# Indexing
a[0]

1

In [15]:
a[-1]

5

In [16]:
a[1:3]

array([2, 3])

In [17]:
a[:3]

array([1, 2, 3])

In [18]:
# Multi Indexing
a[0],a[2],a[4]

(1, 3, 5)

In [19]:
a[[0, 2, -1]]

array([1, 3, 5])

Array Types

In [20]:
a

array([1, 2, 3, 4, 5])

In [21]:
a.dtype

dtype('int64')

In [22]:
# Creating an Array and Specify Type
np.array([1,2,3,4,5],dtype=np.float)

<ipython-input-22-edeaece4e3f4>:2: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  np.array([1,2,3,4,5],dtype=np.float)


array([1., 2., 3., 4., 5.])

Dimensions and Shape

In [23]:
# Multi-Dimentional Array - Matrix
# 3 by 3 array
b = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [24]:
# 2 by 3 array
c = np.array([[1, 2, 3],[4, 5, 6]])
c

array([[1, 2, 3],
       [4, 5, 6]])

In [25]:
c.shape

(2, 3)

In [26]:
# Three Dimentional Array
d = np.array([[[1, 2, 3],[4, 5, 6]],
              [[7, 8, 9], [3, 2, 1]]
              ])
d


array([[[1, 2, 3],
        [4, 5, 6]],

       [[7, 8, 9],
        [3, 2, 1]]])

In [27]:
d.shape

(2, 2, 3)

In [28]:
# Obtain Dimention
d.ndim

3

In [29]:
# Count Elements
d.size

12

In [30]:
# Index and Slice Matrix
sq = np.array([
#     0, 1, 2
      [1,2,3], #0
      [4,5,6], #1
      [7,8,9]  #2
               ])


In [31]:
sq

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [32]:
sq[1]

array([4, 5, 6])

In [33]:
sq[:2, :2]

array([[1, 2],
       [4, 5]])

In [34]:
sq[0,0] = np.array([9])

In [35]:
sq

array([[9, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [36]:
sq[0] = np.array([9,8,7])

In [37]:
sq

array([[9, 8, 7],
       [4, 5, 6],
       [7, 8, 9]])

Summary Statistics

In [38]:
# Mean of the Matrix
sq.mean()

7.0

In [39]:
# Sum the entire matrix
sq.sum()

63

In [40]:
# Sum of each column
sq.sum(axis=0)

array([20, 21, 22])

In [41]:
# Sum of each row
sq.sum(axis=1)

array([24, 15, 24])

In [42]:
# Standard deviation of the matrix
sq.std()

1.632993161855452

In [43]:
# Standard deviation of each columns
sq.std(axis=0)

array([2.05480467, 1.41421356, 1.24721913])

Broadcasting and Vectorized Operations

In [44]:
a = np.arange(4)
a

array([0, 1, 2, 3])

In [45]:
a/10

array([0. , 0.1, 0.2, 0.3])

In [46]:
a

array([0, 1, 2, 3])

In [47]:
a+=2
a

array([2, 3, 4, 5])

In [48]:
l = [0,1,2,3]
l

[0, 1, 2, 3]

In [49]:
[i*10 for i in l]

[0, 10, 20, 30]

In [50]:
a = np.arange(4)
a

array([0, 1, 2, 3])

In [51]:
b = np.array([5,5,5,5])
b

array([5, 5, 5, 5])

In [52]:
a*b

array([ 0,  5, 10, 15])

In [53]:
a/b

array([0. , 0.2, 0.4, 0.6])

Boolean Arrays

In [54]:
a = np.arange(4)
a

array([0, 1, 2, 3])

In [55]:
a[0], a[-1]

(0, 3)

In [56]:
a[[True, False, False, True]]

array([0, 3])

In [57]:
a>=2

array([False, False,  True,  True])

In [58]:
a[a>=2]

array([2, 3])

In [59]:
a.mean()

1.5

In [60]:
a[a>a.mean()]

array([2, 3])

In [61]:
a[(a==0) | (a==1)]

array([0, 1])

In [62]:
A = np.random.randint(100, size=(3,3))
A

array([[94, 73, 59],
       [25,  6, 57],
       [70, 83,  6]])

In [63]:
A[np.array([
    [True, False, True],
    [False, True, False],
    [True, False, True]
     ])]

array([94, 59,  6, 70,  6])

In [64]:
A>30

array([[ True,  True,  True],
       [False, False,  True],
       [ True,  True, False]])

In [65]:
A[A>30]

array([94, 73, 59, 57, 70, 83])

Linear Algebra

In [66]:
A = np.array([
    [1,2,4],
    [4,5,6],
    [7,8,9]
])

In [67]:
B = np.array([
    [6,5],
    [4,3],
    [7,1]
])

In [68]:
A.dot(B)

array([[ 42,  15],
       [ 86,  41],
       [137,  68]])

In [69]:
A@B

array([[ 42,  15],
       [ 86,  41],
       [137,  68]])

In [70]:
A.T

array([[1, 4, 7],
       [2, 5, 8],
       [4, 6, 9]])

In [71]:
A

array([[1, 2, 4],
       [4, 5, 6],
       [7, 8, 9]])

In [72]:
B.T @ A

array([[ 71,  88, 111],
       [ 24,  33,  47]])

Size of Objects in Memory

In [73]:
# An integer is 24bytes
sys.getsizeof(1)

28

In [74]:
# Longs are larger
sys.getsizeof(10**100)

72

In [75]:
# Numpy is much smaller
np.dtype(int).itemsize

8

In [76]:
# List are larger
sys.getsizeof([1])

64

In [77]:
# An array of one element in numpy
np.array([1]).nbytes

8

Performance

In [78]:
l = list(range(50))

In [79]:
a= np.arange(1000)

In [80]:
%time np.sum(a**2)

CPU times: user 186 µs, sys: 21 µs, total: 207 µs
Wall time: 1.72 ms


332833500

In [81]:
%time np.sum([x**2 for x in l])

CPU times: user 174 µs, sys: 1.05 ms, total: 1.23 ms
Wall time: 1.66 ms


40425